[package]
name = "display"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.8"
distributions = { path = "../distributions" }
utilities = { path = "../utilities" }
settings = { path = "../settings" }
